blog/forms.py
from wtforms import Form, StringField, TextAreaField


class PostTextAreaField(TextAreaField):
    def process_formdata(self, valuelist):
        if valuelist:
            self.data = valuelist[0].replace('\r\n', '\n')
        else:
            self.data = ''


class PostForm(Form):
    title = StringField('Title')
    slug = StringField('Slug')
    text = PostTextAreaField('Text', render_kw={'rows':5})

blog/__init__.py
from flask import Blueprint


blog = Blueprint('blog', __name__)

from . import errors, views

blog/views.py
from flask import render_template, request, redirect, url_for
from flask_security import login_required, current_user

from models.models import Post, Tag, Category
from models import db
from utils.utils import get_option_value
from .forms import PostForm
from . import blog


@blog.route('/search/<query>')
def post_search(query):
    q = request.args.get('q')
    if q:
        return redirect(url_for('blog.post_search', query=q))
    posts = db.session.execute(db.select(Post).filter(
            Post.title.contains(query) | Post.text.contains(query)
    )).scalars().all()
    return render_template('blog/post_search.html', posts=posts, favicon=get_option_value('favicon'),
                            blog_title=get_option_value('title'), query=query)

@blog.route('/')
def index():
    q = request.args.get('q')
    if q:
        return redirect(url_for('blog.post_search', query=q))

    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    page = db.paginate(db.select(Post).order_by(Post.created.desc()), page=page,
                       per_page=int(get_option_value('posts_per_page')))

    return render_template('blog/posts.html', page=page, favicon=get_option_value('favicon'),
                           max=max, min=min, blog_title=get_option_value('title'))

@blog.route('/<slug>')
def post_detail(slug):
    q = request.args.get('q')
    if q:
        return redirect(url_for('blog.post_search', query=q))

    post = db.one_or_404(db.select(Post).filter_by(slug=slug))
    category = db.one_or_404(db.select(Category).filter_by(id=post.category_id))
    return render_template('blog/post_detail.html', post=post, category=category,
                           blog_title=get_option_value('title'), favicon=get_option_value('favicon'))

@blog.route('/tags/<slug>')
def tag_detail(slug):
    q = request.args.get('q')
    if q:
        return redirect(url_for('blog.post_search', query=q))
    tag = db.one_or_404(db.select(Tag).filter_by(slug=slug))
    return render_template('blog/tag_detail.html', tag=tag, title=tag.name,
                           blog_title=get_option_value('title'), favicon=get_option_value('favicon'))

@blog.route('/categories/<id>')
def category_detail(id):
    q = request.args.get('q')
    if q:
        return redirect(url_for('blog.post_search', query=q))
    category = db.one_or_404(db.select(Category).filter_by(id=id))
    return render_template('blog/category_detail.html', category=category, title=category.name,
                           blog_title=get_option_value('title'), favicon=get_option_value('favicon'))

# @blog.route('/create', methods=['POST', 'GET'])
# @login_required
# def post_create():
#     form = PostForm() 
    
#     if request.method == 'POST':
#         title = request.form.get('title')
#         text = request.form.get('text')
        
#         try:
#             post = Post(title=title, text=text)
#             db.session.add(post)
#             db.session.commit()
#             return redirect(url_for('posts.post_detail', slug=post.slug))
#         except:
#             print('cannot create a post!!!')

#     return render_template('blog/post_create.html', form=form, blog_title=get_option_value('title'))

# @blog.route('/<slug>/edit', methods=['POST', 'GET'])
# @login_required
# def post_update(slug):
#     q = request.args.get('q')
#     if q:
#         return redirect(url_for('blog.post_search', query=q))
#     post = db.one_or_404(db.select(Post).filter_by(slug=slug))

#     if request.method == 'POST':
#         form = PostForm(formdata=request.form, obj=post)
#         form.populate_obj(post)
#         db.session.commit()
#         return redirect(url_for('blog.post_detail', slug=post.slug))
    
#     form = PostForm(obj=post)
#     return render_template('blog/post_edit.html', post=post, form=form,
#                            blog_title=get_option_value('title'), favicon=get_option_value('favicon'))

templates/blog/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block title %}
  <title>{{ blog_title }}</title>
  {% endblock %}
  {% block icon %}
  <link rel="shortcut icon" href="{{ favicon }}" type="image/x-icon">
  {% endblock %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
  <link href="/static/css/style.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
    integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.0/dist/jquery.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
  {% block additional_css_and_script %}
  {% endblock %}
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark mb-3 shadow" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('blog.index') }}">{{ blog_title }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if current_user.has_role('admin') %}
          <li class="nav-item">
            <a class="nav-link" href="/admin">Admin</a>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex" role="search" method="GET">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  <div class="container" id="main">
    <div class="row">
      <div class="col-9 mx-auto">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>
  <footer class="mt-3 p-3" id="footer">
    <p>Copyright © 2023 {{ blog_title }}</p>
    <p>Powered by TinyBlog</p>
  </footer>
  <script>
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
  </script>
</body>

</html>

templates/blog/category_detail.html
{% extends 'blog/base.html' %}

{% block title %}
  <title>Posts in {{ category.name }} - {{ blog_title }}</title>
{% endblock%}

{% block content %}
  <h1>Post in the "{{ category.name }}" category</h1>
  {% for post in category.posts %}
    {% include 'blog/includes/card.html' %}
  {% endfor %}
{% endblock %}

templates/blog/post_create.html
{% extends 'blog/base.html' %}

{% block title %}
  <title>Create New Post - {{ blog_title }}</title>
{% endblock%}

{% block content %}
    <h1>Create New Post</h1>
    <form action="{{ url_for('blog.post_create') }}" method="post">
        {% for field in form %}
          <div class="form-group mb-3">
            {{ field.label() }}
            {{ field(class="form-control") }}
          </div>
        {% endfor %}
        <button class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block additional_css_and_script %}
<link rel="stylesheet" href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.7.0/build/styles/github-dark.min.css">
<link rel="stylesheet" href="/static/css/lightbox.min.css">
<script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.7.0/build/highlight.min.js"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-chtml.js"></script>
<script type="text/javascript" src="/static/js/lightbox.min.js"></script>
{% endblock %}

{% block title %}
<title>{{ post.title }} - {{ blog_title }}</title>
{% endblock%}

{% block content %}
<h1 id="post-title">{{ post.title }}</h1>
<ul class="list-inline text-mute">
  {% if post.authors|length %}
  <li>
    <span>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person"
        viewBox="0 0 16 16">
        <path
          d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z" />
      </svg>
    </span>
    <span class="visually-hidden">author: </span>
    {% for author in post.authors %}
    <a href="#" class="no-underline no-highlight black-bold-hover">{{ author.name }}</a>
    {% endfor %}
  </li>
  {% endif %}
  <li data-bs-toggle="tooltip" data-bs-title="Created at {{ post.get_time(post.created, '%Y-%m-%d %H:%M:%S') }}">
    <span>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clock"
        viewBox="0 0 16 16">
        <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z" />
        <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z" />
      </svg>
    </span>
    <span class="visually-hidden">created time: </span>
    <time>{{ post.get_time(post.created, '%Y-%m-%d') }}</time>
  </li>
  {% if post.tags|length %}
  <li>
    <span>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-tags"
        viewBox="0 0 16 16">
        <path
          d="M3 2v4.586l7 7L14.586 9l-7-7H3zM2 2a1 1 0 0 1 1-1h4.586a1 1 0 0 1 .707.293l7 7a1 1 0 0 1 0 1.414l-4.586 4.586a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 2 6.586V2z" />
        <path
          d="M5.5 5a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm0 1a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3zM1 7.086a1 1 0 0 0 .293.707L8.75 15.25l-.043.043a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 0 7.586V3a1 1 0 0 1 1-1v5.086z" />
      </svg>
    </span>
    <span class="visually-hidden">tags: </span>
    <span>
      {% for tag in post.tags %}
      <a href="{{ url_for('blog.tag_detail', slug=tag.slug)}}" class="no-highlight no-underline black-bold-hover">{{
        tag.name }}</a>
      {% endfor %}
    </span>
  </li>
  {% endif %}
  <li>
    <span>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-basket"
        viewBox="0 0 16 16">
        <path
          d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1v4.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 13.5V9a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h1.217L5.07 1.243a.5.5 0 0 1 .686-.172zM2 9v4.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V9H2zM1 7v1h14V7H1zm3 3a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 4 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 6 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 8 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5z" />
      </svg>
    </span>
    <span class="visually-hidden">category: </span>
    <span>
      <a href="{{ url_for('blog.category_detail', id=category.id)}}"
        class="no-highlight no-underline black-bold-hover">{{ category.name }}</a>
    </span>
  </li>
</ul>
<div class="col" id="post-content">
  {{ post.convert_text() | safe }}
</div>
<div class="row show-foot">
  <div class="notebook col">
    <span data-bs-toggle="tooltip"
      data-bs-title="Last Modified: {{ post.get_time(post.modified, '%Y-%m-%d %H:%M:%S') }}">Last Modified: {{
      post.get_time(post.modified, '%Y-%m-%d') }}</span>
  </div>
  <div class="copyright col">
    <span data-bs-toggle="tooltip"
      data-bs-title="Please keep the original source link when reposting this article, as the copyright belongs to the author.">©Allow
      normative reprinting.</span>
  </div>
</div>
<script>
  hljs.highlightAll();
  $(document).ready(function () {
    $('#post-content img').each(function () {
      var src_link = $(this).attr('src');
      var caption = $(this).attr('alt')
      $(this).wrap("<a href='" + src_link + "' data-lightbox='post-img' data-title='" + caption + "'></a>");
    })
  })
</script>
{% endblock %}

templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block title %}
  <title>Edit {{ post.title }} - {{ blog_title }}</title>
{% endblock%}

{% block content %}
    <h1>Edit Post "{{ post.title }}"</h1>
    <form action="{{ url_for('blog.post_update', slug=post.slug) }}" method="POST">
        {% for field in form %}
          <div class="form-group mb-3">
            {{ field.label() }}
            {{ field(class="form-control") }}
          </div>
        {% endfor %}
        <button class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

templates/blog/post_search.html
{% extends 'blog/base.html' %}

{% block title %}
<title>Posts containing "{{ query }}" - {{ blog_title }}</title>
{% endblock %}

{% block content %}
<div>
	<h1>
			<span class="title-icons">
				<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-vector-pen" viewBox="0 0 16 16">
					<path fill-rule="evenodd" d="M10.646.646a.5.5 0 0 1 .708 0l4 4a.5.5 0 0 1 0 .708l-1.902 1.902-.829 3.313a1.5 1.5 0 0 1-1.024 1.073L1.254 14.746 4.358 4.4A1.5 1.5 0 0 1 5.43 3.377l3.313-.828L10.646.646zm-1.8 2.908-3.173.793a.5.5 0 0 0-.358.342l-2.57 8.565 8.567-2.57a.5.5 0 0 0 .34-.357l.794-3.174-3.6-3.6z"/>
					<path fill-rule="evenodd" d="M2.832 13.228 8 9a1 1 0 1 0-1-1l-4.228 5.168-.026.086.086-.026z"/>
				</svg>
			</span>
			Search Results
	</h1>
	<div>{{ posts|length }} results found for <b>{{ query }}</b></div>
</div>
{% for post in posts %}
{% include 'blog/includes/card.html' %}
{% endfor %}
{% endblock %}

templates/blog/posts.html
{% extends 'blog/base.html' %}

{% block title %}
<title>{{ blog_title }}</title>
{% endblock%}

{% block content %}
<h1>Posts</h1>
{% for post in page %}
{% include 'blog/includes/card.html' %}
{% endfor %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item {% if not page.has_prev %} disabled {% endif %}">
      <a class="page-link" href="./?page={{ page.prev_num }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% if page.pages <= 9 %} {% for page_num in range(1, page.pages+1) %} <li
      class="page-item {% if page_num == page.page %} active {% endif %}">
      <a class="page-link" href="./?page={{ page_num }}">{{ page_num }}</a>
      </li>
      {% endfor %}
      {% else %}
      <li class="page-item {% if page.page == 1 %} active {% endif %}">
        <a class="page-link" href="./?page=1">1</a>
      </li>
      {% if page.page > 5 %}
      <li class="page-item disabled"><a class="page-link">...</a></li>
      {% endif %}
      {% for page_num in range(max(page.page-3, 2), min(page.page+3, page.pages-1)+1) %}
      <li class="page-item {% if page_num == page.page %} active {% endif %}">
        <a class="page-link" href="./?page={{ page_num }}">{{ page_num }}</a>
      </li>
      {% endfor %}
      {% if page.page <= page.pages - 5 %} <li class="page-item disabled"><a class="page-link">...</a></li>
        {% endif %}
        <li class="page-item {% if page.page == page.pages %} active {% endif %}">
          <a class="page-link" href="./?page={{ page.pages }}">{{ page.pages }}</a>
        </li>
        {% endif %}
        <li class="page-item {% if not page.has_next %} disabled {% endif %}">
          <a class="page-link" href="./?page={{ page.next_num }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
  </ul>
</nav>
{% endblock %}

templates/blog/tag_detail.html
{% extends 'blog/base.html' %}

{% block title %}
  <title>Posts with {{ tag.name }} tag - {{ blog_title }}</title>
{% endblock%}

{% block content %}
  <h1>Post with the "{{ tag.name }}" tag</h1>
  {% for post in tag.posts %}
    {% include 'blog/includes/card.html' %}
  {% endfor %}
{% endblock %}